language: node_js
node_js:
  - 0.10
branches:
  only:
    - master
    - dev
notifications:
  email:
    - rv.maksim@gmail.com
    - angularjs.rus@gmail.com
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - grunt clean buildall docs uglify copy write compress
script:
  - grunt test:unit --browsers Firefox --reporters=dots
  - grunt test:e2e --browsers PhantomJS --reporters=dots
after_success:
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then echo "DEV BRANCH DOESN'T PUSH TO HEROKU"; exit 0; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then exit 0; fi;
      wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh;
      git remote add heroku git@heroku.com:angular-doc.git;
      echo "Host heroku.com" >> ~/.ssh/config;
      echo "   StrictHostKeyChecking no" >> ~/.ssh/config;
      echo "   CheckHostIP no" >> ~/.ssh/config;
      echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config;
      heroku keys:clear;
      yes | heroku keys:add;
      yes | git push heroku master; fi
env:
  global:
  - secure: ! 'YxUgd7mlHqvYwdFBfMr82uoUup48l8RzSToqdX/N/mazZQZjY9e4U7CGuU4j

      60CoHfZmje4NXWatX7fj0UfJDn53yCSztPNA9t09toLIT3bDbtMSqu3g/AE7

      MPzoXjtlbIXGS6wO4U+zWY+mMyEg2rQftmrjPQugZsvk105LtNM='
